/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type BetDeployed = ContractEventLog<{
  _deployedBet: string;
  0: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface BetFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): BetFactory;
  clone(): BetFactory;
  methods: {
    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    /**
     * Creates a new Bet
     * @param description Description of the bet
     * @param expirationTime Timestamp when the bet expires/can be judged upon
     */
    createBet(
      deposit: number | string | BN,
      description: string,
      expirationTime: number | string | BN
    ): NonPayableTransactionObject<string>;

    setBetAddress(_address: string): NonPayableTransactionObject<void>;

    setMapperAddress(_address: string): NonPayableTransactionObject<void>;

    setExchangeAddress(_address: string): NonPayableTransactionObject<void>;

    /**
     * Returns an array of all deployed bet instances
     */
    getBets(): NonPayableTransactionObject<string[]>;

    /**
     * verifies if a bet is deployed
     * @param _address bet address to check
     */
    isBetDeployed(_address: string): NonPayableTransactionObject<boolean>;
  };
  events: {
    BetDeployed(cb?: Callback<BetDeployed>): EventEmitter;
    BetDeployed(
      options?: EventOptions,
      cb?: Callback<BetDeployed>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "BetDeployed", cb: Callback<BetDeployed>): void;
  once(
    event: "BetDeployed",
    options: EventOptions,
    cb: Callback<BetDeployed>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
