/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IBPool extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): IBPool;
  clone(): IBPool;
  methods: {
    swapExactAmountIn(
      arg0: string,
      arg1: number | string | BN,
      arg2: string,
      arg3: number | string | BN,
      arg4: number | string | BN
    ): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;

    swapExactAmountOut(
      arg0: string,
      arg1: number | string | BN,
      arg2: string,
      arg3: number | string | BN,
      arg4: number | string | BN
    ): NonPayableTransactionObject<{
      0: string;
      1: string;
    }>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
