/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface QuickSwapExchangeTest extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): QuickSwapExchangeTest;
  clone(): QuickSwapExchangeTest;
  methods: {
    MATIC(): NonPayableTransactionObject<string>;

    QUICK(): NonPayableTransactionObject<string>;

    WETH(): NonPayableTransactionObject<string>;

    factory(): NonPayableTransactionObject<string>;

    maUSDC(): NonPayableTransactionObject<string>;

    swapEthForMaUSDC(
      unixTime: number | string | BN
    ): NonPayableTransactionObject<void>;

    swapMaUSDCForEth(
      unixTime: number | string | BN
    ): NonPayableTransactionObject<void>;

    sendEthToOwner(): NonPayableTransactionObject<void>;

    getTokenBalance(
      target: string,
      token: string
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
