#!/bin/bash

if [ "$BRANCH" = "main" ]; then
    CONTRACT_ADDRESS=${CA_PROD}
    API_URL=${API_URL_PROD}
    BET_MAPPER_ADDRESS=${BET_MAPPER_PROD}
    ONBOARD_API_KEY=${ONBOARD_API_KEY_PROD}
elif [ "$BRANCH" = "develop" ]; then
    CONTRACT_ADDRESS=${CA_DEVELOP}
    API_URL=${API_URL_DEVELOP}
    BET_MAPPER_ADDRESS=${BET_MAPPER_DEVELOP}
    ONBOARD_API_KEY=${ONBOARD_API_KEY_DEVELOP}
fi

echo "NEXT_PUBLIC_API_URL=${API_URL}" > .env
echo "NEXT_PUBLIC_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}" >> .env
echo "NEXT_PUBLIC_BET_MAPPER_ADDRESS=${BET_MAPPER_ADDRESS}" >> .env
echo "NEXT_PUBLIC_ONBOARD_API_KEY=${ONBOARD_API_KEY}" >> .env
